import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const project = dirname(fileURLToPath(import.meta.url));
const output = resolve(project, 'dist');
const manifest = JSON.parse(await readFile(resolve(project, 'project.manifest.json'), 'utf8'));
const executedTargets = manifest.targetPlatforms;
if (!Array.isArray(executedTargets) || executedTargets.length !== 1 || executedTargets[0] !== 'web') {
  throw new Error('Local sample build refuses non-web execution claims.');
}
const executedTarget = 'web';
const requestedTarget = manifest.starter?.requestedTargetPlatform || executedTarget;
const mechanic = manifest.starter?.mechanic || 'collect';
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
const gameConfig = JSON.stringify({ name: manifest.name, objective: manifest.objective, target: requestedTarget, executedTarget, mechanic }).replaceAll('<', '\\u003c');
const mechanicCopy = {
  collect: 'Collect the green beacon',
  dodge: 'Reach the green exit while avoiding red hazards',
  survive: 'Avoid red hazards for 10 seconds'
}[mechanic];
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await writeFile(resolve(output, 'game.txt'), 'sample-game build artifact\n', 'utf8');
await writeFile(resolve(output, 'build.json'), JSON.stringify({ name: manifest.name, objective: manifest.objective, target: requestedTarget, executedTarget, mechanic, format: 'local-demo', version: 3 }, null, 2) + '\n', 'utf8');
await writeFile(resolve(output, 'index.html'), `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(manifest.name)}</title><style>
html,body{margin:0;height:100%;overflow:hidden;background:#0d1016;color:#fff;font-family:system-ui,sans-serif}canvas{display:block;width:100%;height:100%}.hud{position:fixed;inset:16px auto auto 16px;max-width:min(560px,calc(100vw - 32px));padding:10px 12px;border:1px solid #ffffff30;border-radius:10px;background:#0b0d11dd}.hud b{color:#d7ff64;font-size:17px}.objective{margin:5px 0;color:#cbd2da}.target{color:#86b7ff}.win{color:#79d99b}.touch{display:${requestedTarget === 'mobile' ? 'grid' : 'none'};position:fixed;right:22px;bottom:22px;grid-template:". up ." 58px "left down right" 58px/58px 58px 58px;gap:6px}.touch button{border:1px solid #ffffff40;border-radius:14px;background:#151a24dd;color:#fff;font-size:24px;touch-action:none}.touch [data-key="w"]{grid-area:up}.touch [data-key="a"]{grid-area:left}.touch [data-key="s"]{grid-area:down}.touch [data-key="d"]{grid-area:right}
</style></head><body><canvas id="game"></canvas><div class="hud"><b>${escapeHtml(manifest.name)}</b><div class="objective">${escapeHtml(manifest.objective)}</div><span class="target">Target: ${escapeHtml(requestedTarget)} (requested) · Local execution: ${escapeHtml(executedTarget)} · Mechanic: ${escapeHtml(mechanic)}</span><br>${requestedTarget === 'mobile' ? 'Use the touch controls' : 'Move with WASD or arrow keys'} · ${escapeHtml(mechanicCopy)}<br><span id="status">Ready to play</span></div><div class="touch" aria-label="Touch movement controls"><button data-key="w" aria-label="Move up">▲</button><button data-key="a" aria-label="Move left">◀</button><button data-key="s" aria-label="Move down">▼</button><button data-key="d" aria-label="Move right">▶</button></div><script>
const config=${gameConfig};
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),keys=new Set(),player={x:80,y:120,r:16},goal={x:520,y:300,r:22},hazards=[{x:260,y:180,r:18,vx:130,vy:90},{x:430,y:390,r:20,vx:-110,vy:120},{x:650,y:220,r:16,vx:90,vy:-140}];let won=false,last=performance.now(),roundStarted=performance.now(),lives=3,statusUntil=0;
function size(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);goal.x=Math.max(80,innerWidth-60);goal.y=Math.max(140,Math.min(300,innerHeight-70));for(const h of hazards){h.x=Math.max(h.r,Math.min(innerWidth-h.r,h.x));h.y=Math.max(h.r,Math.min(innerHeight-h.r,h.y))}}addEventListener('resize',size);size();
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(['arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('[data-key]').forEach(button=>{const key=button.dataset.key;button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);keys.add(key)});for(const type of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(type,()=>keys.delete(key))});
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!won){let x=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft')),y=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'));const n=Math.hypot(x,y)||1;player.x=Math.max(player.r,Math.min(innerWidth-player.r,player.x+x/n*220*dt));player.y=Math.max(player.r,Math.min(innerHeight-player.r,player.y+y/n*220*dt));let hit=false;if(config.mechanic!=='collect'){for(const h of hazards){h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.x<h.r||h.x>innerWidth-h.r)h.vx*=-1;if(h.y<h.r||h.y>innerHeight-h.r)h.vy*=-1;if(Math.hypot(player.x-h.x,player.y-h.y)<player.r+h.r)hit=true}if(hit){player.x=80;player.y=120;if(config.mechanic==='dodge'){document.querySelector('#status').textContent='Collision — returned to start';statusUntil=now+1000}else{lives-=1;roundStarted=now;if(lives===0){lives=3;document.querySelector('#status').textContent='Round failed — three lives lost';statusUntil=now+1200}else{document.querySelector('#status').textContent='Hit — '+lives+' lives left';statusUntil=now+1000}}}}if(config.mechanic==='collect'&&now-roundStarted>=15000){player.x=80;player.y=120;roundStarted=now;document.querySelector('#status').textContent='Time expired — beacon reset';statusUntil=now+1000}const reached=Math.hypot(player.x-goal.x,player.y-goal.y)<player.r+goal.r;if((config.mechanic!=='survive'&&reached)||(config.mechanic==='survive'&&now-roundStarted>=10000)){won=true;document.querySelector('#status').textContent=config.mechanic==='survive'?'Playtest complete — survived 10 seconds!':config.mechanic==='dodge'?'Playtest complete — exit reached!':'Playtest complete — beacon collected!';document.querySelector('#status').className='win'}else if(config.mechanic==='survive'&&now>=statusUntil)document.querySelector('#status').textContent='Survive: '+Math.max(0,Math.ceil((10000-(now-roundStarted))/1000))+'s · '+lives+' lives'}ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#151a24';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.strokeStyle='#252d3b';for(let x=0;x<innerWidth;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,innerHeight);ctx.stroke()}for(let y=0;y<innerHeight;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}if(config.mechanic!=='survive'){ctx.shadowBlur=25;ctx.shadowColor='#d7ff64';ctx.fillStyle='#d7ff64';ctx.beginPath();ctx.arc(goal.x,goal.y,goal.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}if(config.mechanic!=='collect'){ctx.fillStyle='#ff6b6b';for(const h of hazards){ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,Math.PI*2);ctx.fill()}}ctx.fillStyle='#86b7ff';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,Math.PI*2);ctx.fill();requestAnimationFrame(frame)}requestAnimationFrame(frame);
</script></body></html>`, 'utf8');
console.log(`built ${output}`);
